### ISSUE TITLE
The 2.0 mac version doesn't seem to open properly.

### ISSUE THREAD

**Issue by jason840709** [ZetaoYang/RcloneBrowser#1]

**Comment by holazt** [comment]
Yeah, I didn't test them completely. Can you post the exact error?

**Comment by jason840709** [comment]
<img width="262" alt="image" src="https://github.com/holazt/RcloneBrowser/assets/110349892/4c596d81-033c-4398-8158-db4ade100c6c">

I only saw this window pop up and nothing more.

**Comment by holazt** [comment]
I think Rclone Browser requires executable permissions, e.g.
```
chmod +x "/Applications/Rclone Browser.app/Contents/MacOS/rclone-browser"
```

refer to https://superuser.com/questions/1345755/how-to-fix-the-application-cant-be-opened-on-mac

**Comment by jason840709** [comment]
Uh... I don't think so? Because the rclone browser 1.8 I installed before has been working fine for years.
